# Generated by Django 2.0.6 on 2018-06-12 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20180612_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('band', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='myapp.Band')),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.AlterField(
            model_name='album',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albuns', to='myapp.Band'),
        ),
    ]
